name: Artillery Socket.IO Load Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_name:
        description: 'Enter a custom name for the workflow run'
        required: true

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run load-tests/load-test.yml --record
        env:
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.APIKEY }}
          SECRETLOGIN: ${{ secrets.SECRETLOGIN }}
          SECRETPASS: ${{ secrets.SECRETPASS }}