name: Playwright + Artillery test on Demand

on:
  workflow_dispatch:

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run load-tests/playwright-load.yml --record
        env:
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.APIKEY }}